import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useEffect } from "react";
import { PLATFORMS, type Platform } from "@/lib/platforms";
import { PlatformIcon } from "@/components/platform-badge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { CheckCircle2, ExternalLink, Unplug, PlugZap, ShieldCheck } from "lucide-react";

type SocialAccount = { id:string; platform:Platform; handle:string; display_name:string; followers:number; connected:boolean; avatar_url?:string|null };
const QUERY_OPTIONS = { staleTime: 30_000, gcTime: 5 * 60_000, refetchOnWindowFocus: false, refetchOnReconnect: false } as const;
export const Route = createFileRoute("/_authenticated/accounts")({ head:()=>({meta:[{title:"Accounts — Orbit"}]}), component:Accounts });
function Accounts(){
 const accounts=useQuery<SocialAccount[]>({queryKey:["social-accounts"],queryFn:async()=>{const r=await fetch("/api/social/accounts");if(!r.ok)throw new Error((await r.json()).error||"Unable to load accounts");return r.json();},...QUERY_OPTIONS});
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("connected"))toast.success("Social account connected successfully");const e=p.get("oauth_error");if(e)toast.error(e);if(p.has("connected")||p.has("oauth_error"))window.history.replaceState({},"","/accounts");},[]);
 const connect=(platform:Platform)=>window.location.assign(`/api/social/oauth/${platform}`);
 const disconnect=async(id:string)=>{const r=await fetch("/api/social/accounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok){toast.error((await r.json()).error||"Unable to disconnect account");return;}toast.success("Account disconnected");await accounts.refetch();};
 return <div className="page-shell mx-auto max-w-[1200px] space-y-5 p-3 sm:space-y-7 sm:p-5 lg:p-8">
  <header><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-primary sm:text-xs"><PlugZap className="h-3.5 w-3.5"/> Connections</div><h1 className="mt-1 text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">Social accounts</h1><p className="mt-1.5 text-sm text-muted-foreground">Connect the channels you manage and keep everything in one workspace.</p></header>
  <div className="flex items-start gap-3 rounded-xl border bg-card p-4 sm:gap-4 sm:p-5"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-600"><ShieldCheck className="h-5 w-5"/></div><div className="min-w-0"><p className="text-sm font-semibold">Secure OAuth connections</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Orbit sends you to each social platform to authorize access. Your profile and available connection details are returned automatically—no manual usernames or follower counts.</p></div></div>
  <div className="grid gap-3 sm:gap-4 lg:grid-cols-2">{PLATFORMS.map(platform=>{const connected=(accounts.data??[]).filter(a=>a.platform===platform.id);return <Card key={platform.id} className="border shadow-none"><CardContent className="p-4 sm:p-5"><div className="flex items-center gap-2.5 sm:gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border bg-muted/30 sm:h-10 sm:w-10"><PlatformIcon platform={platform.id} className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{platform.name}</h2><p className="mt-0.5 truncate text-xs text-muted-foreground">{connected.length?`${connected.length} connected account${connected.length>1?"s":""}`:platform.connectionLabel}</p></div><Button size="sm" className="shrink-0" variant={connected.length?"outline":"default"} onClick={()=>connect(platform.id)}><ExternalLink className="mr-1.5 h-3.5 w-3.5"/>{connected.length?"Add":"Connect"}</Button></div><div className="mt-4 border-t pt-4">{connected.length===0?<div className="py-5 text-center text-xs text-muted-foreground">No {platform.name} account connected.</div>:<ul className="space-y-2">{connected.map(a=><li key={a.id} className="flex items-center gap-2.5 rounded-lg border bg-muted/10 p-3 sm:gap-3">{a.avatar_url?<img src={a.avatar_url} alt="" loading="lazy" decoding="async" className="h-9 w-9 shrink-0 rounded-full object-cover"/>:<div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-muted"><PlatformIcon platform={platform.id} className="h-4 w-4"/></div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{a.display_name}</p><p className="truncate text-xs text-muted-foreground">{a.handle}{a.followers?` · ${a.followers.toLocaleString()} followers`:""}</p></div><span className="hidden items-center gap-1 text-[11px] font-medium text-emerald-600 sm:flex"><CheckCircle2 className="h-3.5 w-3.5"/>Connected</span><Button size="icon" variant="ghost" className="shrink-0" title="Disconnect" onClick={()=>disconnect(a.id)}><Unplug className="h-4 w-4"/></Button></li>)}</ul>}</div></CardContent></Card>})}</div>
 </div>;
}
