/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsGoogleRouteImport } from './routes/api/tts-google'
import { Route as ApiTtsElevenlabsRouteImport } from './routes/api/tts-elevenlabs'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiRepurposeRouteImport } from './routes/api/repurpose'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedRepurposeRouteImport } from './routes/_authenticated/repurpose'
import { Route as AuthenticatedPresetsRouteImport } from './routes/_authenticated/presets'
import { Route as AuthenticatedMotivationalVideosRouteImport } from './routes/_authenticated/motivational-videos'
import { Route as AuthenticatedLyricalVideosRouteImport } from './routes/_authenticated/lyrical-videos'
import { Route as AuthenticatedKidVideosRouteImport } from './routes/_authenticated/kid-videos'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedImagesToVideoRouteImport } from './routes/_authenticated/images-to-video'
import { Route as AuthenticatedGamingVideosRouteImport } from './routes/_authenticated/gaming-videos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedKidVideosIndexRouteImport } from './routes/_authenticated/kid-videos.index'
import { Route as AuthenticatedGamingVideosIndexRouteImport } from './routes/_authenticated/gaming-videos.index'
import { Route as AuthenticatedKidVideosWyrRouteImport } from './routes/_authenticated/kid-videos.wyr'
import { Route as AuthenticatedKidVideosEmojiRouteImport } from './routes/_authenticated/kid-videos.emoji'
import { Route as AuthenticatedGamingVideosRankingRouteImport } from './routes/_authenticated/gaming-videos.ranking'
import { Route as AuthenticatedGamingVideosNewsRouteImport } from './routes/_authenticated/gaming-videos.news'
import { Route as AuthenticatedGamingVideosMemesRouteImport } from './routes/_authenticated/gaming-videos.memes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsGoogleRoute = ApiTtsGoogleRouteImport.update({
  id: '/api/tts-google',
  path: '/api/tts-google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsElevenlabsRoute = ApiTtsElevenlabsRouteImport.update({
  id: '/api/tts-elevenlabs',
  path: '/api/tts-elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepurposeRoute = ApiRepurposeRouteImport.update({
  id: '/api/repurpose',
  path: '/api/repurpose',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepurposeRoute = AuthenticatedRepurposeRouteImport.update({
  id: '/repurpose',
  path: '/repurpose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresetsRoute = AuthenticatedPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotivationalVideosRoute =
  AuthenticatedMotivationalVideosRouteImport.update({
    id: '/motivational-videos',
    path: '/motivational-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLyricalVideosRoute =
  AuthenticatedLyricalVideosRouteImport.update({
    id: '/lyrical-videos',
    path: '/lyrical-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKidVideosRoute = AuthenticatedKidVideosRouteImport.update({
  id: '/kid-videos',
  path: '/kid-videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesToVideoRoute =
  AuthenticatedImagesToVideoRouteImport.update({
    id: '/images-to-video',
    path: '/images-to-video',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamingVideosRoute =
  AuthenticatedGamingVideosRouteImport.update({
    id: '/gaming-videos',
    path: '/gaming-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKidVideosIndexRoute =
  AuthenticatedKidVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKidVideosRoute,
  } as any)
const AuthenticatedGamingVideosIndexRoute =
  AuthenticatedGamingVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGamingVideosRoute,
  } as any)
const AuthenticatedKidVideosWyrRoute =
  AuthenticatedKidVideosWyrRouteImport.update({
    id: '/wyr',
    path: '/wyr',
    getParentRoute: () => AuthenticatedKidVideosRoute,
  } as any)
const AuthenticatedKidVideosEmojiRoute =
  AuthenticatedKidVideosEmojiRouteImport.update({
    id: '/emoji',
    path: '/emoji',
    getParentRoute: () => AuthenticatedKidVideosRoute,
  } as any)
const AuthenticatedGamingVideosRankingRoute =
  AuthenticatedGamingVideosRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedGamingVideosRoute,
  } as any)
const AuthenticatedGamingVideosNewsRoute =
  AuthenticatedGamingVideosNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AuthenticatedGamingVideosRoute,
  } as any)
const AuthenticatedGamingVideosMemesRoute =
  AuthenticatedGamingVideosMemesRouteImport.update({
    id: '/memes',
    path: '/memes',
    getParentRoute: () => AuthenticatedGamingVideosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gaming-videos': typeof AuthenticatedGamingVideosRouteWithChildren
  '/images-to-video': typeof AuthenticatedImagesToVideoRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/kid-videos': typeof AuthenticatedKidVideosRouteWithChildren
  '/lyrical-videos': typeof AuthenticatedLyricalVideosRoute
  '/motivational-videos': typeof AuthenticatedMotivationalVideosRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/repurpose': typeof AuthenticatedRepurposeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/repurpose': typeof ApiRepurposeRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts-google': typeof ApiTtsGoogleRoute
  '/gaming-videos/memes': typeof AuthenticatedGamingVideosMemesRoute
  '/gaming-videos/news': typeof AuthenticatedGamingVideosNewsRoute
  '/gaming-videos/ranking': typeof AuthenticatedGamingVideosRankingRoute
  '/kid-videos/emoji': typeof AuthenticatedKidVideosEmojiRoute
  '/kid-videos/wyr': typeof AuthenticatedKidVideosWyrRoute
  '/gaming-videos/': typeof AuthenticatedGamingVideosIndexRoute
  '/kid-videos/': typeof AuthenticatedKidVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/images-to-video': typeof AuthenticatedImagesToVideoRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/lyrical-videos': typeof AuthenticatedLyricalVideosRoute
  '/motivational-videos': typeof AuthenticatedMotivationalVideosRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/repurpose': typeof AuthenticatedRepurposeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/repurpose': typeof ApiRepurposeRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts-google': typeof ApiTtsGoogleRoute
  '/gaming-videos/memes': typeof AuthenticatedGamingVideosMemesRoute
  '/gaming-videos/news': typeof AuthenticatedGamingVideosNewsRoute
  '/gaming-videos/ranking': typeof AuthenticatedGamingVideosRankingRoute
  '/kid-videos/emoji': typeof AuthenticatedKidVideosEmojiRoute
  '/kid-videos/wyr': typeof AuthenticatedKidVideosWyrRoute
  '/gaming-videos': typeof AuthenticatedGamingVideosIndexRoute
  '/kid-videos': typeof AuthenticatedKidVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gaming-videos': typeof AuthenticatedGamingVideosRouteWithChildren
  '/_authenticated/images-to-video': typeof AuthenticatedImagesToVideoRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/kid-videos': typeof AuthenticatedKidVideosRouteWithChildren
  '/_authenticated/lyrical-videos': typeof AuthenticatedLyricalVideosRoute
  '/_authenticated/motivational-videos': typeof AuthenticatedMotivationalVideosRoute
  '/_authenticated/presets': typeof AuthenticatedPresetsRoute
  '/_authenticated/repurpose': typeof AuthenticatedRepurposeRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/api/repurpose': typeof ApiRepurposeRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts-google': typeof ApiTtsGoogleRoute
  '/_authenticated/gaming-videos/memes': typeof AuthenticatedGamingVideosMemesRoute
  '/_authenticated/gaming-videos/news': typeof AuthenticatedGamingVideosNewsRoute
  '/_authenticated/gaming-videos/ranking': typeof AuthenticatedGamingVideosRankingRoute
  '/_authenticated/kid-videos/emoji': typeof AuthenticatedKidVideosEmojiRoute
  '/_authenticated/kid-videos/wyr': typeof AuthenticatedKidVideosWyrRoute
  '/_authenticated/gaming-videos/': typeof AuthenticatedGamingVideosIndexRoute
  '/_authenticated/kid-videos/': typeof AuthenticatedKidVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/compose'
    | '/dashboard'
    | '/gaming-videos'
    | '/images-to-video'
    | '/inbox'
    | '/kid-videos'
    | '/lyrical-videos'
    | '/motivational-videos'
    | '/presets'
    | '/repurpose'
    | '/videos'
    | '/api/repurpose'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/api/tts-google'
    | '/gaming-videos/memes'
    | '/gaming-videos/news'
    | '/gaming-videos/ranking'
    | '/kid-videos/emoji'
    | '/kid-videos/wyr'
    | '/gaming-videos/'
    | '/kid-videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/compose'
    | '/dashboard'
    | '/images-to-video'
    | '/inbox'
    | '/lyrical-videos'
    | '/motivational-videos'
    | '/presets'
    | '/repurpose'
    | '/videos'
    | '/api/repurpose'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/api/tts-google'
    | '/gaming-videos/memes'
    | '/gaming-videos/news'
    | '/gaming-videos/ranking'
    | '/kid-videos/emoji'
    | '/kid-videos/wyr'
    | '/gaming-videos'
    | '/kid-videos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/compose'
    | '/_authenticated/dashboard'
    | '/_authenticated/gaming-videos'
    | '/_authenticated/images-to-video'
    | '/_authenticated/inbox'
    | '/_authenticated/kid-videos'
    | '/_authenticated/lyrical-videos'
    | '/_authenticated/motivational-videos'
    | '/_authenticated/presets'
    | '/_authenticated/repurpose'
    | '/_authenticated/videos'
    | '/api/repurpose'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/api/tts-google'
    | '/_authenticated/gaming-videos/memes'
    | '/_authenticated/gaming-videos/news'
    | '/_authenticated/gaming-videos/ranking'
    | '/_authenticated/kid-videos/emoji'
    | '/_authenticated/kid-videos/wyr'
    | '/_authenticated/gaming-videos/'
    | '/_authenticated/kid-videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiRepurposeRoute: typeof ApiRepurposeRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsElevenlabsRoute: typeof ApiTtsElevenlabsRoute
  ApiTtsGoogleRoute: typeof ApiTtsGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-google': {
      id: '/api/tts-google'
      path: '/api/tts-google'
      fullPath: '/api/tts-google'
      preLoaderRoute: typeof ApiTtsGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-elevenlabs': {
      id: '/api/tts-elevenlabs'
      path: '/api/tts-elevenlabs'
      fullPath: '/api/tts-elevenlabs'
      preLoaderRoute: typeof ApiTtsElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repurpose': {
      id: '/api/repurpose'
      path: '/api/repurpose'
      fullPath: '/api/repurpose'
      preLoaderRoute: typeof ApiRepurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repurpose': {
      id: '/_authenticated/repurpose'
      path: '/repurpose'
      fullPath: '/repurpose'
      preLoaderRoute: typeof AuthenticatedRepurposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presets': {
      id: '/_authenticated/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AuthenticatedPresetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivational-videos': {
      id: '/_authenticated/motivational-videos'
      path: '/motivational-videos'
      fullPath: '/motivational-videos'
      preLoaderRoute: typeof AuthenticatedMotivationalVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lyrical-videos': {
      id: '/_authenticated/lyrical-videos'
      path: '/lyrical-videos'
      fullPath: '/lyrical-videos'
      preLoaderRoute: typeof AuthenticatedLyricalVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kid-videos': {
      id: '/_authenticated/kid-videos'
      path: '/kid-videos'
      fullPath: '/kid-videos'
      preLoaderRoute: typeof AuthenticatedKidVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images-to-video': {
      id: '/_authenticated/images-to-video'
      path: '/images-to-video'
      fullPath: '/images-to-video'
      preLoaderRoute: typeof AuthenticatedImagesToVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gaming-videos': {
      id: '/_authenticated/gaming-videos'
      path: '/gaming-videos'
      fullPath: '/gaming-videos'
      preLoaderRoute: typeof AuthenticatedGamingVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kid-videos/': {
      id: '/_authenticated/kid-videos/'
      path: '/'
      fullPath: '/kid-videos/'
      preLoaderRoute: typeof AuthenticatedKidVideosIndexRouteImport
      parentRoute: typeof AuthenticatedKidVideosRoute
    }
    '/_authenticated/gaming-videos/': {
      id: '/_authenticated/gaming-videos/'
      path: '/'
      fullPath: '/gaming-videos/'
      preLoaderRoute: typeof AuthenticatedGamingVideosIndexRouteImport
      parentRoute: typeof AuthenticatedGamingVideosRoute
    }
    '/_authenticated/kid-videos/wyr': {
      id: '/_authenticated/kid-videos/wyr'
      path: '/wyr'
      fullPath: '/kid-videos/wyr'
      preLoaderRoute: typeof AuthenticatedKidVideosWyrRouteImport
      parentRoute: typeof AuthenticatedKidVideosRoute
    }
    '/_authenticated/kid-videos/emoji': {
      id: '/_authenticated/kid-videos/emoji'
      path: '/emoji'
      fullPath: '/kid-videos/emoji'
      preLoaderRoute: typeof AuthenticatedKidVideosEmojiRouteImport
      parentRoute: typeof AuthenticatedKidVideosRoute
    }
    '/_authenticated/gaming-videos/ranking': {
      id: '/_authenticated/gaming-videos/ranking'
      path: '/ranking'
      fullPath: '/gaming-videos/ranking'
      preLoaderRoute: typeof AuthenticatedGamingVideosRankingRouteImport
      parentRoute: typeof AuthenticatedGamingVideosRoute
    }
    '/_authenticated/gaming-videos/news': {
      id: '/_authenticated/gaming-videos/news'
      path: '/news'
      fullPath: '/gaming-videos/news'
      preLoaderRoute: typeof AuthenticatedGamingVideosNewsRouteImport
      parentRoute: typeof AuthenticatedGamingVideosRoute
    }
    '/_authenticated/gaming-videos/memes': {
      id: '/_authenticated/gaming-videos/memes'
      path: '/memes'
      fullPath: '/gaming-videos/memes'
      preLoaderRoute: typeof AuthenticatedGamingVideosMemesRouteImport
      parentRoute: typeof AuthenticatedGamingVideosRoute
    }
  }
}

interface AuthenticatedGamingVideosRouteChildren {
  AuthenticatedGamingVideosMemesRoute: typeof AuthenticatedGamingVideosMemesRoute
  AuthenticatedGamingVideosNewsRoute: typeof AuthenticatedGamingVideosNewsRoute
  AuthenticatedGamingVideosRankingRoute: typeof AuthenticatedGamingVideosRankingRoute
  AuthenticatedGamingVideosIndexRoute: typeof AuthenticatedGamingVideosIndexRoute
}

const AuthenticatedGamingVideosRouteChildren: AuthenticatedGamingVideosRouteChildren =
  {
    AuthenticatedGamingVideosMemesRoute: AuthenticatedGamingVideosMemesRoute,
    AuthenticatedGamingVideosNewsRoute: AuthenticatedGamingVideosNewsRoute,
    AuthenticatedGamingVideosRankingRoute:
      AuthenticatedGamingVideosRankingRoute,
    AuthenticatedGamingVideosIndexRoute: AuthenticatedGamingVideosIndexRoute,
  }

const AuthenticatedGamingVideosRouteWithChildren =
  AuthenticatedGamingVideosRoute._addFileChildren(
    AuthenticatedGamingVideosRouteChildren,
  )

interface AuthenticatedKidVideosRouteChildren {
  AuthenticatedKidVideosEmojiRoute: typeof AuthenticatedKidVideosEmojiRoute
  AuthenticatedKidVideosWyrRoute: typeof AuthenticatedKidVideosWyrRoute
  AuthenticatedKidVideosIndexRoute: typeof AuthenticatedKidVideosIndexRoute
}

const AuthenticatedKidVideosRouteChildren: AuthenticatedKidVideosRouteChildren =
  {
    AuthenticatedKidVideosEmojiRoute: AuthenticatedKidVideosEmojiRoute,
    AuthenticatedKidVideosWyrRoute: AuthenticatedKidVideosWyrRoute,
    AuthenticatedKidVideosIndexRoute: AuthenticatedKidVideosIndexRoute,
  }

const AuthenticatedKidVideosRouteWithChildren =
  AuthenticatedKidVideosRoute._addFileChildren(
    AuthenticatedKidVideosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamingVideosRoute: typeof AuthenticatedGamingVideosRouteWithChildren
  AuthenticatedImagesToVideoRoute: typeof AuthenticatedImagesToVideoRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedKidVideosRoute: typeof AuthenticatedKidVideosRouteWithChildren
  AuthenticatedLyricalVideosRoute: typeof AuthenticatedLyricalVideosRoute
  AuthenticatedMotivationalVideosRoute: typeof AuthenticatedMotivationalVideosRoute
  AuthenticatedPresetsRoute: typeof AuthenticatedPresetsRoute
  AuthenticatedRepurposeRoute: typeof AuthenticatedRepurposeRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamingVideosRoute: AuthenticatedGamingVideosRouteWithChildren,
  AuthenticatedImagesToVideoRoute: AuthenticatedImagesToVideoRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedKidVideosRoute: AuthenticatedKidVideosRouteWithChildren,
  AuthenticatedLyricalVideosRoute: AuthenticatedLyricalVideosRoute,
  AuthenticatedMotivationalVideosRoute: AuthenticatedMotivationalVideosRoute,
  AuthenticatedPresetsRoute: AuthenticatedPresetsRoute,
  AuthenticatedRepurposeRoute: AuthenticatedRepurposeRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiRepurposeRoute: ApiRepurposeRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsElevenlabsRoute: ApiTtsElevenlabsRoute,
  ApiTtsGoogleRoute: ApiTtsGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
